#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py collectstatic --noinput

pip install debugpy -t /tmp
python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client  manage.py test

