#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

# lifespan protocol doesn't work with Django 3.0.
# See this ticket: https://code.djangoproject.com/ticket/31508
uvicorn config.asgi:application --host 0.0.0.0 --reload

