# Generated by Django 2.2.3 on 2020-02-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0027_remove_siteconfiguration_site"),
        ("users", "0004_auto_20191001_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="site_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siteconfiguration",
                to="brokerage.SiteConfiguration",
            ),
        ),
    ]
