# Generated by Django 2.2.3 on 2020-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_site_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goesternid',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that external_user_id already exists.'}, help_text='Not Required. 32 characters or fewer. Has to be unique if not Null.', max_length=32, null=True, unique=True, verbose_name='external_user_id'),
        ),
    ]
