# Generated by Django 2.2.3 on 2020-02-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20200213_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="site_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_site_configurations",
                to="brokerage.SiteConfiguration",
            ),
        ),
    ]
