# Generated by Django 2.2.3 on 2020-02-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200217_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_users', to='brokerage.SiteConfiguration'),
        ),
    ]
