# Generated by Django 3.0.6 on 2020-07-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_curator',
        ),
    ]
