# Generated by Django 3.0.6 on 2020-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_agreed_to_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agreed_to_privacy",
            field=models.BooleanField(default=False),
        ),
    ]
