# Generated by Django 3.0.6 on 2021-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210420_1433'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externaluserid',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_id_for_user'),
        ),
    ]
