# Generated by Django 2.2.3 on 2020-03-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(help_text='Enter a descriptive title for this instance', max_length=128)),
                ('url', models.CharField(help_text='Url to which requests will be sent to', max_length=256)),
                ('authentication_string', models.CharField(blank=True, default='', help_text='In cases where an archive demands some sort of pre-build authentication string or sentence, it is entered here. E.g. ENAs authentication', max_length=128)),
                ('username', models.CharField(default='', help_text='In case of username/password authentication fill this field', max_length=72)),
                ('password', models.CharField(default='', help_text='In case of username/password authentication fill this field', max_length=72)),
                ('comment', models.TextField(blank=True, default='', help_text='Enter a description or helpful text here')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(help_text='Enter a descriptive title for this instance.', max_length=128, unique=True)),
                ('contact', models.EmailField(help_text='Main contact to address in case of something. This will, in any case, serve as a fallback when no other person can be determined.', max_length=254)),
                ('release_submissions', models.BooleanField(default=False, help_text='If this field is unchecked (default), all submission requests by this site have to be manually approved by staff members. If checked all submissions will be automatically send to the respective archives.')),
                ('jira_project_key', models.CharField(choices=[('SAND', 'SAND'), ('DSUB', 'DSUB')], default='SAND', max_length=4)),
                ('comment', models.TextField(default='', help_text='Enter a description or helpful text here.')),
                ('ena_ftp', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to connect to access ENA FTP-server.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.ena_ftp+', to='generic.ResourceCredential')),
                ('ena_report_server', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to obtain reports via ENA services.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.ena_report_server+', to='generic.ResourceCredential')),
                ('ena_server', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to connect to ENA.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.ena_server+', to='generic.ResourceCredential')),
                ('helpdesk_server', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to connect to a JIRA based helpdesk system. In 99 % of all cases this means the GFBio JIRA helpdesk.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.helpdesk_server+', to='generic.ResourceCredential')),
                ('pangaea_jira_server', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to connect to Pangaea-Jira. This Serverrepresents the actual jira-instance of Pangaea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.pangaea_jira_server+', to='generic.ResourceCredential')),
                ('pangaea_token_server', models.ForeignKey(blank=True, help_text='Select which server and/or account this configuration should use to connect to Pangaea token server. Via this server, thetoken necessary to access Pangaea-Jira is obtained', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SiteConfiguration.pangaea_token_server+', to='generic.ResourceCredential')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('P', 'Pangaea JIRA'), ('G', 'GFBio-Helpdesk JIRA')], max_length=1)),
                ('label', models.CharField(default='', max_length=256)),
                ('site_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generic.SiteConfiguration')),
            ],
        ),
    ]
