# Generated by Django 3.0.6 on 2020-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_auto_20200525_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.IntegerField(choices=[(0, 'not available'), (1, 'POST'), (2, 'GET'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE')], default=0, help_text='Http method used, if available'),
        ),
    ]
