# Generated by Django 4.0.8 on 2023-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generic", "0009_auto_20200526_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcecredential",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ticketlabel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
