# Generated by Django 4.1 on 2023-09-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("generic", "0010_alter_resourcecredential_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="pangaea_jira_server",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which server and/or account this configuration should use to connect to Pangaea-Jira. This Server represents the actual jira-instance of Pangaea",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="SiteConfiguration.pangaea_jira_server+",
                to="generic.resourcecredential",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="pangaea_token_server",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which server and/or account this configuration should use to connect to Pangaea token server. Via this server, the token necessary to access Pangaea-Jira is obtained",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="SiteConfiguration.pangaea_token_server+",
                to="generic.resourcecredential",
            ),
        ),
    ]
