# Generated by Django 4.1 on 2024-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0002_fieldtype_field_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="target",
            field=models.CharField(
                choices=[("ENA", "ENA"), ("ENA_PANGAEA", "ENA_PANGAEA"), ("GENERIC", "GENERIC"), ("ATAX", "ATAX")],
                default="GENERIC",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="fieldtype",
            name="type",
            field=models.SlugField(max_length=32),
        ),
    ]
