# Generated by Django 4.1 on 2024-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0003_profile_target_alter_fieldtype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldtype",
            name="type",
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
