# Generated by Django 4.1 on 2024-05-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0006_field_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="inherit_fields_from",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="submission_profile.profile"
            ),
        ),
    ]
