# Generated by Django 4.1 on 2024-05-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0007_profile_inherit_fields_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="inherit_fields_from",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="submission_profile.profile"
            ),
        ),
    ]
