# Generated by Django 4.1 on 2024-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0009_alter_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="default",
            field=models.TextField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="field",
            name="mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="field",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
