# Generated by Django 4.1 on 2024-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0010_field_default_field_mandatory_field_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fields",
            field=models.ManyToManyField(blank=True, to="submission_profile.field"),
        ),
    ]
