# Generated by Django 4.1 on 2024-06-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0012_alter_field_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option", models.CharField(max_length=128)),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submission_profile.field"),
                ),
            ],
        ),
    ]
