# Generated by Django 4.1 on 2024-06-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0013_fieldoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldoption",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="options", to="submission_profile.field"
            ),
        ),
    ]
