# Generated by Django 4.1 on 2024-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0014_alter_fieldoption_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldoption",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="fieldoption",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
