# Generated by Django 4.1 on 2024-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0015_alter_fieldoption_options_fieldoption_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldoption",
            name="description",
            field=models.TextField(blank=True, default="", help_text="May be displayed depending on field_type."),
        ),
        migrations.AddField(
            model_name="fieldoption",
            name="help_link",
            field=models.URLField(blank=True, default="", help_text="May be displayed depending on field_type."),
        ),
    ]
