# Generated by Django 4.1 on 2024-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0016_fieldoption_description_fieldoption_help_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="system_wide_mandatory",
            field=models.BooleanField(default=False),
        ),
    ]
