# Generated by Django 4.1 on 2024-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0017_field_system_wide_mandatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="system_wide_profile",
            field=models.BooleanField(default=False),
        ),
    ]
