# Generated by Django 4.1 on 2024-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0019_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
