# Generated by Django 4.1 on 2024-07-29 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submission_profile", "0022_field_order_field_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fields",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="inherit_fields_from",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProfileFieldExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "placeholder",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descriptive text displayed within the input field unless it is filled out",
                    ),
                ),
                ("system_wide_mandatory", models.BooleanField(default=False)),
                ("mandatory", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True)),
                ("default", models.TextField(blank=True, default="", max_length=64)),
                (
                    "order",
                    models.IntegerField(default=100, help_text="Rank within in the elements in the layout-position"),
                ),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submission_profile.field"),
                ),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submission_profile.profile"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
