# Generated by Django 4.1 on 2024-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0023_remove_profile_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_user_profile",
            field=models.BooleanField(default=False),
        ),
    ]
