# Generated by Django 4.1 on 2024-09-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0025_delete_profilefieldextension"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "placeholder",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descriptive text displayed within the input field unless it is filled out",
                    ),
                ),
                ("system_wide_mandatory", models.BooleanField(default=False)),
                ("mandatory", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True)),
                ("default", models.TextField(blank=True, default="", max_length=64)),
                (
                    "order",
                    models.IntegerField(default=100, help_text="Rank within in the elements in the layout-position"),
                ),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submission_profile.field"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="fields",
            field=models.ManyToManyField(through="submission_profile.ProfileField", to="submission_profile.field"),
        ),
        migrations.AddField(
            model_name="profilefield",
            name="profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submission_profile.profile"),
        ),
    ]
