# Generated by Django 4.1 on 2024-09-27 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0026_profilefield_profile_fields_profilefield_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilefield",
            name="placeholder",
        ),
        migrations.RemoveField(
            model_name="profilefield",
            name="system_wide_mandatory",
        ),
    ]
