# Generated by Django 4.1 on 2024-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0026_remove_field_default_remove_field_mandatory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="inherit_fields_from",
        ),
        migrations.RemoveField(
            model_name="profilefieldextension",
            name="system_wide_mandatory",
        ),
        migrations.AddField(
            model_name="field",
            name="system_wide_mandatory",
            field=models.BooleanField(default=False),
        ),
    ]
