# Generated by Django 4.1 on 2024-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0027_remove_profile_inherit_fields_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilefieldextension",
            name="system_wide_mandatory",
            field=models.BooleanField(default=False),
        ),
    ]
