# Generated by Django 4.1 on 2024-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0028_remove_field_default_remove_field_mandatory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilefield",
            name="mandatory",
            field=models.BooleanField(default=True),
        ),
    ]
