# Generated by Django 4.1 on 2024-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0029_field_default_field_mandatory_field_placeholder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilefieldextension",
            name="order",
            field=models.IntegerField(default=100, help_text="Rank within in the elements in the layout-position"),
        ),
    ]
