# Generated by Django 4.1 on 2024-09-30 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0029_alter_profilefield_mandatory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilefield",
            name="order",
        ),
    ]
