# Generated by Django 4.1 on 2024-10-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0030_remove_profilefield_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilefield",
            name="default",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default value for this field. If the 'field' is a system-wide-mandatory field, the value cannot be changed and will stay blank",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="profilefield",
            name="field",
            field=models.ForeignKey(
                help_text="The corresponding Field of this instance",
                on_delete=django.db.models.deletion.CASCADE,
                to="submission_profile.field",
            ),
        ),
        migrations.AlterField(
            model_name="profilefield",
            name="mandatory",
            field=models.BooleanField(
                default=True,
                help_text="Whether this field is mandatory or not. If the 'field' is a system-wide-mandatory field, the value cannot be set, thus is always True",
            ),
        ),
        migrations.AlterField(
            model_name="profilefield",
            name="profile",
            field=models.ForeignKey(
                help_text="The profile this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="submission_profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profilefield",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this field is visible or not.If the 'field' is a system-wide-mandatory field, the value cannot be changed and will stay True ",
            ),
        ),
    ]
