# Generated by Django 4.1 on 2025-02-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0031_alter_profilefield_default_alter_profilefield_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="submission_profile.profile",
            ),
        ),
    ]
