# Generated by Django 4.1 on 2025-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_profile", "0032_profile_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilefield",
            name="default",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default value for this field. If the 'field' is a system-wide-mandatory field, the value cannot be changed and will stay blank",
                max_length=128,
            ),
        ),
    ]
