version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }
  django_media: { }

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gfbio_submissions_production_django
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    logging:
      driver: syslog
      options:
        tag: 'GFBio-django'
    restart: always
    networks:
      - default
    volumes:
      - django_media:/app/gfbio_submissions/media
      - type: tmpfs
        target: /mnt/s3bucket
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gfbio_submissions_production_postgres
    networks:
      - default
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: gfbio_submissions_production_traefik
    networks:
      - default
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    restart: always

  redis:
    image: redis:6
    networks:
      - default
    restart: always

  celeryworker:
    <<: *django
    image: gfbio_submissions_production_celeryworker
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-worker'
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: gfbio_submissions_production_celerybeat
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-beat'
    command: /start-celerybeat

  flower:
    <<: *django
    image: gfbio_submissions_production_flower
    logging:
      driver: syslog
      options:
        tag: 'GFBio-flower'
    command: /start-flower
