version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}
  django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
      # TODO: 23.11.2018: from gds src. I comment this for comparision. Redis should be sufficient as broker.
      # - rabbit
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/gfbio_submissions/media
      # git has to be initialized, remote origin has to be set.
      - /var/www/gfbio-submission-auditing:/gfbio-submission-auditing
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.0
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # TODO: 23.11.2018: from gds src. I comment this for comparision. Redis should be sufficient as broker.
  # https://stackoverflow.com/questions/43264838/celery-when-should-you-choose-redis-as-a-message-broker-over-rabbitmq
  #  rabbit:
  #    hostname: rabbit
  #    image: rabbitmq:latest
  #    env_file: .env
  #    #    ports:
  #    #      - "5672"  # we forward this port because it's useful for debugging
  #    #      - "15672"  # here, we can access rabbitmq management plugin

  celeryworker:
    <<: *django
    depends_on:
      - postgres
      - redis
      # TODO: 23.11.2018: from gds src. I comment this for comparision. Redis should be sufficient as broker.
      # - rabbit
    command: /start-celeryworker.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/gfbio_submissions/media
      - /var/www/gfbio-submission-auditing:/gfbio-submission-auditing

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - redis
      # TODO: 23.11.2018: from gds src. I comment this for comparision. Redis should be sufficient as broker.
      # - rabbit
    command: /start-celerybeat.sh

