version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gfbio_submissions_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/gfbio_submissions/media
    logging:
      driver: syslog
      options:
        tag: 'GFBio-django'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gfbio_submissions_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: gfbio_submissions_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-worker'
    image: gfbio_submissions_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-beat'
    image: gfbio_submissions_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    logging:
      driver: syslog
      options:
        tag: 'GFBio-flower'
    image: gfbio_submissions_production_flower
    command: /start-flower
