version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  django_media: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gfbio_submissions_production_django
    container_name: gfbio-django
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    logging:
      driver: syslog
      options:
        tag: 'GFBio-django'
    restart: always
    networks:
      - default
      - internalProxy
    volumes:
      - django_media:/app/gfbio_submissions/media
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gfbio_submissions_production_postgres
    container_name: gfbio-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    networks:
      - default
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  redis:
    image: redis:6
    container_name: gfbio-redis
    networks:
      - default
    restart: always

  celeryworker:
    <<: *django
    image: gfbio_submissions_production_celeryworker
    container_name: gfbio-celeryworker
    networks:
      - default
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-worker'
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: gfbio_submissions_production_celerybeat
    container_name: gfbio-celerybeat
    networks:
      - default
    logging:
      driver: syslog
      options:
        tag: 'GFBio-celery-beat'
    command: /start-celerybeat

  flower:
    <<: *django
    image: gfbio_submissions_production_flower
    container_name: gfbio-flower
    networks:
      - default
    logging:
      driver: syslog
      options:
        tag: 'GFBio-flower'
    command: /start-flower

networks:
  default:
  internalProxy:
    external:
      name: internalProxy
