#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

s3fs "$DJANGO_AWS_STORAGE_BUCKET_NAME" "$DJANGO_S3FS_MOUNT_POINT" -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o url="$DJANGO_AWS_S3_ENDPOINT_URL"

exec celery -A config.celery_app worker -l INFO -Q default --concurrency=4
