#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

s3fs "$DJANGO_AWS_STORAGE_BUCKET_NAME" "$DJANGO_S3FS_MOUNT_POINT" -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o url="$DJANGO_AWS_S3_ENDPOINT_URL"

python /app/manage.py shell << EOF
from django.contrib.auth import get_user_model;
User = get_user_model();
User.objects.create_superuser("adminuser", "adminuser@dev.com", "adminuser")
EOF

python /app/manage.py loaddata /app/cicd/test_data.json
python /app/manage.py loaddata /app/gfbio_submissions/fixtures/jira_messages.json

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
