#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

python /app/manage.py shell <<EOF
from django.contrib.auth import get_user_model;
User = get_user_model();
User.objects.create_superuser("adminuser", "adminuser@dev.com", "adminuser")
EOF

python /app/manage.py loaddata /app/cicd/test_data.json
python /app/manage.py loaddata /app/gfbio_submissions/fixtures/jira_messages.json

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
