#!/bin/bash

set -o errexit
set -o nounset

# when needed for local testing with CELERY_ALWAYS_EAGER=False: s3fs "$DJANGO_AWS_STORAGE_BUCKET_NAME" "$DJANGO_S3FS_MOUNT_POINT" -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o url="$DJANGO_AWS_S3_ENDPOINT_URL"

if [ "${MOUNT_S3FS:-false}" = "True" ]; then
  echo "Mounting S3FS. MOUNT_S3FS=${MOUNT_S3FS}"
  echo "$DJANGO_AWS_STORAGE_BUCKET_NAME" "$DJANGO_S3FS_MOUNT_POINT" -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o url="$DJANGO_AWS_S3_ENDPOINT_URL"
  s3fs "$DJANGO_AWS_STORAGE_BUCKET_NAME" "$DJANGO_S3FS_MOUNT_POINT" -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o url="$DJANGO_AWS_S3_ENDPOINT_URL"
else
  echo "Not mounting S3FS. MOUNT_S3FS is set to False or not existing."
fi

exec watchfiles celery.__main__.main --args '-A config.celery_app worker -l INFO -Q default --concurrency=4'
