# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='target',
            field=models.CharField(choices=[('ENA', 'ENA'), ('ENA_PANGAEA', 'ENA_PANGAEA'), ('GENERIC', 'GENERIC')], max_length=16),
        ),
    ]
