# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_auto_20181120_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditabletextdata',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='brokerobject',
            name='created',
        ),
        migrations.RemoveField(
            model_name='brokerobject',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='persistentidentifier',
            name='created',
        ),
        migrations.RemoveField(
            model_name='persistentidentifier',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='primarydatafile',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='submissionfileupload',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='taskprogressreport',
            name='modified',
        ),
    ]
