# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 13:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gfbio_submissions.brokerage.utils.submission_tools
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokerage', '0004_auto_20190124_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(help_text='The actual file uploaded.', upload_to=gfbio_submissions.brokerage.utils.submission_tools.submission_upload_path)),
                ('site', models.ForeignKey(blank=True, help_text='Related "Site". E.g. gfbio-portal or silva.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='embargo',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 26), null=True),
        ),
        migrations.AddField(
            model_name='submissionupload',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Submission associated with this Upload.', null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerage.Submission'),
        ),
        migrations.AddField(
            model_name='submissionupload',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Related "User". A real person that uses the submission frontend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
