# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0005_auto_20190226_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionupload',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Related "User". E.g. a real person that uses the submission frontend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
