# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0006_auto_20190226_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionupload',
            name='attach_to_ticket',
            field=models.BooleanField(default=False, help_text='When checked, thus having True as value, every uploaded file will be attached to the main helpdesk ticketassociated with "submission".'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='embargo',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 27), null=True),
        ),
    ]
