# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0007_auto_20190227_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarydatafile',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionfileupload',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
