# Generated by Django 2.2.3 on 2019-11-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0008_auto_20191025_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmissionFileUpload',
        ),
    ]
