# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0008_auto_20190227_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='embargo',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 5), null=True),
        ),
    ]
