# Generated by Django 2.2.3 on 2019-11-14 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0009_delete_submissionfileupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrimaryDataFile",
        ),
    ]
