# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0009_auto_20190306_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centername',
            name='center_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='submission',
            name='embargo',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 6), null=True),
        ),
    ]
