# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-28 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0010_auto_20190307_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='embargo',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 27), null=True),
        ),
    ]
