# Generated by Django 2.2.3 on 2019-11-14 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0010_delete_primarydatafile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="gfbio_server",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="use_gfbio_services",
        ),
    ]
