# Generated by Django 2.2.3 on 2019-11-28 13:33

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0012_auto_20191115_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentidentifier',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='persistentidentifier',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
