# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0012_auto_20190426_1212'),
        ('brokerage', '0012_auto_20190428_2119'),
    ]

    operations = [
    ]
