# Generated by Django 2.2.3 on 2019-12-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0013_auto_20191128_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionupload',
            name='md5_checksum',
            field=models.CharField(default='', help_text='MD5 checksum of "file"', max_length=32),
        ),
    ]
