# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0013_merge_20190428_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionupload',
            name='meta_data',
            field=models.BooleanField(default=False, help_text='A True/checked value means that this file contains meta-data.'),
        ),
    ]
