# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0014_submissionupload_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionupload',
            name='attachment_id',
            field=models.IntegerField(blank=True, help_text='If file is attached to a ticket, it might be useful to store the primary identifier of the attachment. Needed e.g. for removing an attachment from a ticket.', null=True),
        ),
    ]
