# Generated by Django 2.2.3 on 2020-01-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0017_auto_20191205_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='created',
        ),
    ]
