# Generated by Django 2.2.3 on 2020-01-15 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0023_auto_20200115_1058"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnaReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("STU", "studies"),
                            ("SAM", "samples"),
                            ("EXP", "experiments"),
                            ("RUN", "runs"),
                        ],
                        default="STU",
                        max_length=3,
                    ),
                ),
                ("report_data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
