# Generated by Django 2.2.3 on 2020-01-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0024_enareport"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="ena_report_server",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which server and/or account this configuration should use to obtain reports via ENA services.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="SiteConfiguration.ena_report_server+",
                to="brokerage.ResourceCredential",
            ),
        ),
    ]
