# Generated by Django 2.2.3 on 2020-03-02 09:59

from django.db import migrations, models
import gfbio_submissions.brokerage.storage
import gfbio_submissions.brokerage.utils.submission_tools


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0026_persistentidentifier_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionupload",
            name="file",
            field=models.FileField(
                help_text="The actual file uploaded.",
                max_length=220,
                storage=gfbio_submissions.brokerage.storage.OverwriteStorage(),
                upload_to=gfbio_submissions.brokerage.utils.submission_tools.submission_upload_path,
            ),
        ),
    ]
