# Generated by Django 2.2.3 on 2020-02-18 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0028_auto_20200213_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokerobject',
            old_name='site',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='submissionupload',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Related "Site". E.g. gfbio-portal or silva.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionupload',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Related "User". E.g. a real person that uses the submission frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
