# Generated by Django 2.2.3 on 2020-02-18 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0032_auto_20200218_1313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionupload",
            name="user",
        ),
    ]
