# Generated by Django 2.2.3 on 2020-03-03 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0028_auto_20200302_1245"),
        ("brokerage", "0034_auto_20200218_1427"),
    ]

    operations = []
