# Generated by Django 2.2.3 on 2020-03-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0035_merge_20200303_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionupload',
            name='md5_checksum',
            field=models.CharField(blank=True, default='', help_text='MD5 checksum of "file"', max_length=32),
        ),
    ]
