# Generated by Django 2.2.3 on 2020-03-27 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20200327_0833"),
        ("brokerage", "0036_auto_20200320_1217"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceCredential",
        ),
        migrations.RemoveField(
            model_name="ticketlabel",
            name="site_configuration",
        ),
        migrations.DeleteModel(
            name="SiteConfiguration",
        ),
        migrations.DeleteModel(
            name="TicketLabel",
        ),
    ]
