# Generated by Django 2.2.3 on 2020-03-27 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0037_auto_20200327_0833"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestLog",
        ),
    ]
