# Generated by Django 2.2.3 on 2020-03-30 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0038_delete_requestlog"),
        ("brokerage", "0036_persistentidentifier_hold_date"),
    ]

    operations = []
