# Generated by Django 2.2.3 on 2020-04-22 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0039_merge_20200330_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
