# Generated by Django 2.2.3 on 2020-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0040_auto_20200422_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentidentifier',
            name='user_notified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
