# Generated by Django 3.0.6 on 2020-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0042_auto_20200721_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentidentifier',
            name='user_notified_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
