# Generated by Django 3.0.6 on 2021-01-21 11:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0044_submission_approval_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(help_text='Some - test <br /> Bar - some bar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
