# Generated by Django 3.0.6 on 2021-04-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0048_auto_20210204_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='site',
        ),
    ]
