# Generated by Django 3.0.6 on 2021-04-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0050_remove_submission_submitting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitting_user_common_information',
        ),
    ]
