# Generated by Django 3.0.6 on 2023-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0051_remove_submission_submitting_user_common_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='target',
            field=models.CharField(choices=[('ENA', 'ENA'), ('ENA_PANGAEA', 'ENA_PANGAEA'), ('GENERIC', 'GENERIC')], max_length=16),
        ),
    ]
