# Generated by Django 4.0.8 on 2023-05-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0053_alter_submission_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='target',
            field=models.CharField(choices=[('ENA', 'ENA'), ('ENA_PANGAEA', 'ENA_PANGAEA'), ('GENERIC', 'GENERIC')], max_length=16),
        ),
    ]
