# Generated by Django 4.0.8 on 2023-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0056_submissionupload_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionupload",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENA", "ENA"),
                    ("ENA_PANGAEA", "ENA_PANGAEA"),
                    ("GENERIC", "GENERIC"),
                    ("ATAX", "ATAX"),
                ],
                default="",
                help_text="optional: field for transferring the submission target to this SubmissionUpload",
                max_length=16,
            ),
        ),
    ]
