# Generated by Django 4.0.8 on 2023-07-31 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0057_alter_submissionupload_target"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionupload",
            name="target",
        ),
    ]
