# Generated by Django 4.1 on 2024-03-20 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0061_alter_auditabletextdata_atax_exp_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditabletextdata",
            name="atax_exp_index",
        ),
        migrations.RemoveField(
            model_name="auditabletextdata",
            name="atax_file_name",
        ),
        migrations.RemoveField(
            model_name="auditabletextdata",
            name="atax_xml_valid",
        ),
    ]
