# Generated by Django 4.1 on 2024-04-05 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0062_remove_auditabletextdata_atax_exp_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("report", models.CharField(max_length=512)),
                (
                    "report_category",
                    models.CharField(choices=[("ERROR", "ERROR"), ("INFO", "INFO"), ("DEBUG", "DEBUG")], max_length=6),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Submission associated with this Report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brokerage.submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
