# Generated by Django 4.1 on 2024-04-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brokerage", "0063_submissionreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionreport",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this SubmissionReport. Same as related submission.user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
