# Generated by Django 4.1 on 2024-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0065_remove_submissionreport_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbcdConversionResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("data_id", models.UUIDField(default=uuid.uuid4)),
                ("xml", models.TextField(blank=True, default="", help_text="Result of the ABCD-Conversion.")),
                (
                    "errors",
                    models.TextField(
                        blank=True, default="", help_text="if errors occured during conversion they show here."
                    ),
                ),
                ("logs", models.TextField(blank=True, default="", help_text="All logs written during conversion.")),
                (
                    "atax_xml_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Result of the validation of the xml structure against abcd xml schema",
                        verbose_name="validation status",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Associated Submission for this object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brokerage.submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
