# Generated by Django 4.1 on 2024-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0066_abcdconversionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="abcdconversionresult",
            name="warnings",
            field=models.TextField(
                blank=True, default="", help_text="if warnings occured during conversion they show here."
            ),
        ),
    ]
