# Generated by Django 4.1 on 2025-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0068_submissioncloudupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissioncloudupload",
            name="file",
        ),
    ]
