# Generated by Django 4.1 on 2025-01-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dt_upload", "0019_dtupload_filesize"),
        ("brokerage", "0069_remove_submissioncloudupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissioncloudupload",
            name="file",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="dt_upload.dtupload"
            ),
            preserve_default=False,
        ),
    ]
