# Generated by Django 4.1 on 2025-01-31 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0070_submissioncloudupload_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissioncloudupload",
            name="file",
        ),
    ]
