# Generated by Django 4.1 on 2025-02-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dt_upload", "0023_fileuploadrequest_s3_location"),
        ("brokerage", "0071_remove_submissioncloudupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissioncloudupload",
            name="file_upload",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dt_upload.fileuploadrequest"
            ),
        ),
    ]
