# Generated by Django 4.1 on 2025-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0072_submissioncloudupload_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissioncloudupload",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("deleted", "Deleted")],
                default="active",
                help_text="Select the status of the upload.",
                max_length=10,
            ),
        ),
    ]
