# Generated by Django 4.1 on 2025-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0073_submissioncloudupload_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissioncloudupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                    ("uploaded", "In our bucket"),
                    ("uploaded_with_checked_checksum", "In our bucket, checksum-check successfull"),
                    ("uploaded_with_bad_checksum", "In our bucket, checksum-check failed"),
                    ("transferred", "File was transferred"),
                    ("transfer_failed", "Tried to transfer file but failed"),
                    ("transferred_with_checked_checksum", "File was transferred, checksum-check successfull"),
                    ("transferred_with_bad_checksum", "File was transferred, checksum-check failed"),
                ],
                default="new",
                help_text="Select the status of the upload.",
                max_length=128,
            ),
        ),
    ]
