# Generated by Django 4.1 on 2026-05-20 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0074_alter_submissioncloudupload_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataValidationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="brokerage.submission"),
                ),
                (
                    "upload_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brokerage.submissioncloudupload"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValidationTaskReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brokerage.metadatavalidationreport"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValidationFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("WARNING", "WARNING"), ("ERROR", "ERROR")], default="ERROR", max_length=10
                    ),
                ),
                ("row", models.IntegerField(null=True)),
                ("column", models.IntegerField(null=True)),
                ("column_name", models.CharField(max_length=255, null=True)),
                ("message", models.TextField()),
                ("help_text", models.TextField()),
                (
                    "task_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brokerage.validationtaskreport"
                    ),
                ),
            ],
        ),
    ]
