# Generated by Django 4.1 on 2026-06-01 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brokerage", "0075_metadatavalidationreport_validationtaskreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatavalidationreport",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered validation. Jira comments are public when this matches submission.user, otherwise internal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metadata_validation_reports_triggered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
