# Generated by Django 4.1 on 2026-07-02 12:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0076_metadatavalidationreport_triggered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraQueueMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("type", models.CharField(choices=[("CHECKSUM_CALCULATED", "CHECKSUM_CALCULATED")], max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_SENT", "Not sent"),
                            ("PICKED_UP", "Picked up"),
                            ("SENT", "Sent"),
                            ("ERROR", "Error"),
                        ],
                        default="NOT_SENT",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField()),
                ("submission_id", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
