# Generated by Django 4.1 on 2026-06-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0076_metadatavalidationreport_triggered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="persistentidentifier",
            name="curators_notified_embargo_expiry_for",
            field=models.DateField(blank=True, null=True),
        ),
    ]
