# Generated by Django 4.1 on 2026-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0078_jiraqueuemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationfinding",
            name="status",
            field=models.CharField(
                choices=[("INFO", "INFO"), ("WARNING", "WARNING"), ("ERROR", "ERROR")], default="ERROR", max_length=10
            ),
        ),
    ]
