# Generated by Django 4.1 on 2026-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0079_alter_validationfinding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationfinding",
            name="finding_type",
            field=models.CharField(default="unclassified", max_length=255),
        ),
    ]
