# Generated by Django 4.1 on 2026-07-31 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0080_validationfinding_finding_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"permissions": [("curate_submissions", "Can edit submissions that belong to other users")]},
        ),
    ]
