# Generated by Django 4.1 on 2026-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokerage", "0080_validationfinding_finding_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [("curate_submissions", "Can edit (curate) submissions that belong to other users")]
            },
        ),
        migrations.AlterField(
            model_name="validationtaskreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("INFO", "INFO"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
